name: Generate Snake Game

on:
  schedule: # atualiza todo dia à meia-noite
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Dreyzyy
          outputs: dist/snake.svg
          background: "1E1B2B"    # cor de fundo similar ao Midnight Purple
          head: "A855F7"           # cabeça da cobrinha (igual ao corpo)
          tail: "A855F7"           # corpo da cobrinha (igual à cabeça)
          food: "FF4C4C"           # cor da comida (frutinha)
          grid: "2A273A"           # cor do grid (linhas do fundo)

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
